### PR TITLE
Update to generate swift instead of objective c source code

### PR DESCRIPTION
**Pull request by tonyxiao**
Modified resource builder in place to build swift file instead of objective c file, tested and works great. However I'm really not that familiar with ruby and not sure how to add a command line option to switch between generating swift vs objective c. Help appreciated!

### CODE REVIEW

**Comment by tonyxiao** [comment]
Swift support allows doing things like this, which is totally awesome

```swift
// xcres extensions

func LS(key: R.Strings, args: CVarArgType...) -> String {
    return NSString(format: NSLocalizedString(key.rawValue, comment: ""),
        arguments: getVaList(args)) as String
}

extension UIImage {
    convenience init?(_ key: R.ImagesAssets) {
        self.init(named: key.rawValue)
    }
}

extension UIFont {
    convenience init!(_ fontName: R.Fonts, size: CGFloat) {
        self.init(name: fontName.rawValue, size: size)
    }
}

let myFont = UIFont(R.Fonts.Custom, size: 15)
let image = UIImage(R.ImagesAssets.logo)

```

**Comment by tonyxiao** [comment]
Or we can extend the very generated enum type itself and add computed property to return corresponding image / font / localized string.

**Comment by tonyxiao** [comment]
This should be a good starting point though!

**Comment by carlossless** [comment]
Regarding the option flag, I would suggest looking at the [project_command.rb](https://github.com/mrackwitz/xcres/blob/master/lib/xcres/command/project_command.rb) file, there's a bunch of options being set up there. As you can tell they just set variables which are latter used in the execution flow of the command you're running.

**Comment by mrackwitz** [comment]
Nice idea! I wanted to add pure/non-bridged Swift support since a while.
But I'd still keep both output formats, the current and Swift, so that you can select one over an optional CLI argument (eg. `xcres --template swift`).
That would also fix the existing integration specs, which fail now. But then it would be also good to add an integration spec, which test the new format, actually.
Yes, that's quite a lot work to do. But this tool is used in production apps. I wouldn't ship an update, which breaks Objective-C compatibility.
@tonyxiao: Are you up to tackle that?

**Comment by timbodeit** [comment]
Done. See #25

**Pull request closed without merging**
