### PR TITLE
Bumped version to 0.7.0

### PR DESCRIPTION
**Pull request by simonseyer**

### CODE REVIEW

**Comment by pietbrauer** [comment]
👋 what's the reason for the version bump? There doesn't seem to be a lot different to v0.6.0 https://github.com/mrackwitz/xcres/compare/v0.6.0...master

**Comment by Eldorado234** [comment]
Hey Piet 👋 😄 The reason is that [Xcodeproj]( https://github.com/CocoaPods/Xcodeproj) made a lot of bug fixes we want to benefit from with  [Phoenx](https://github.com/jensmeder/Phoenx) (especially https://github.com/CocoaPods/Xcodeproj/pull/427 which will hopefully be part of the next release). 

This version bump for xcres would allow us to use both tools with same Xcodeproj version. It is probably also beneficial for the compatibility with other tools that rely on xcodeproj.

Hope your are well :-)

**Comment by pietbrauer** [comment]
Hey Simon, nice hearing from you again 😊.

I don't see why the version should be changed. `xcres` [requires `xcodeproj` to be higher than `1.2` and smaller than `2.0`](https://github.com/mrackwitz/xcres/blob/master/xcres.gemspec#L41). To take advantage of the new `xcodeproj` in your project, you would have to do a `bundle update xcodeproj` (Modifying *your* `Gemfile.lock`).

The changes made in this PR would not change anything there as `xcres` gets imported from the `xcres.gemspec`, which was not modified in this PullRequest.

**Comment by Eldorado234** [comment]
Yeah, that's true. Mixed this up.

However, there are two weird things happening.

---

```rb
source "https://rubygems.org"

gem "phoenx", "~> 0.2.0"
gem "xcres"
```
 leads to
```
Bundler could not find compatible versions for gem "xcodeproj":
  In Gemfile:
    xcodeproj

    phoenx (~> 0.2.0) was resolved to 0.2.1, which depends on
      xcodeproj (~> 1.3)

    xcres was resolved to 0.4.0, which depends on
      xcodeproj (~> 0.18)
```
So it resolves `xcres` to the wrong version (`0.4.0`)

---

When forcing it to `0.6.0`
```rb
source "https://rubygems.org"

gem "phoenx", "~> 0.2.0"
gem "xcres", "~> 0.6.0"
```

it still references the wrong `xcodeproj` version

```
Bundler could not find compatible versions for gem "xcodeproj":
  In Gemfile:
    xcodeproj

    xcres (~> 0.6.0) was resolved to 0.6.0, which depends on
      xcodeproj (< 1.1.0, >= 0.28.2)
```

---

With my fork where these changes are merged and where I've created a `v0.7.0` tag everything works fine.

Do you have an idea @pietbrauer why this happens?

Cheers

**Comment by pietbrauer** [comment]
Can you use this master branch? Seems to me that https://github.com/mrackwitz/xcres/commit/4868175bd17ee43caec01c0185cee58e05e7e511 has not made it into a release yet.

**Comment by Eldorado234** [comment]
Yep. So just doing this release should be right way to go, isn't it?

**Comment by pietbrauer** [comment]
Jep. Would love to integrate #34 as well

**Comment by Eldorado234** [comment]
Yeah, but it seems there are still some tests outstanding. Do you think you find the time to add some?

**Comment by pietbrauer** [comment]
🆒, seems `master` is working for you. I will close this one if favour of #36.

**Pull request closed without merging**
